### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by farevildee** [Imberflur/veloren-snap#5]
game won't start

**Comment by timsueberkrueb** [comment]
Hey @farevildee, thanks for reporting a bug.

Please provide the following details about your problem:
* Log you get when running Veloren from the terminal (please use [paste.ubuntu.com](https://paste.ubuntu.com/) or a similar service and post the link)
* Operating system and version
* Graphics card and graphics driver (`sudo lshw -C video`)
* Are you using Wayland or X11 ([how to find out](https://askubuntu.com/a/990224))?

Please **make sure** your system supports Vulkan and that you have [Vulkan installed on your system](https://linuxconfig.org/install-and-test-vulkan-on-linux) (there's also [a guide on the Arch Linux wiki](https://wiki.archlinux.org/title/Vulkan#Installation)). Unfortunately, Veloren dropped OpenGL support and requires Vulkan now.

Please also install `vulkan-tools` (e.g. `apt install vulkan-tools` on Ubuntu) and run:

```
vulkaninfo
```

and submit the output (it's pretty long, so please use [paste.ubuntu.com](https://paste.ubuntu.com/), [paste.gg](https://paste.gg), or a similar service and post the link).

Next, we have to test whether this is a snap-specific issue or a Veloren specific issue.
The easiest way to do so is for you to [download Veloren](https://veloren.net/download/) using a method other than snap (e.g. using [this tarball](https://github.com/veloren/airshipper/releases/latest/download/airshipper-linux.tar.gz)) and test if that works.

Thanks for your help in debugging this issue!

**Comment by Imberflur** [comment]
Closing since no additional info has been provided. Please re-open or create a new issue if this persists and provide the information requested above!
